default color preset: use bold blue for better visibility
The default color preset works fine on dark background, with one
exception: blue characters are hardly readable. So let's make
(most of) these bold.
Even bold blue is fine on light background, so this sould not make
anything worse.

Addresses #1013